version: "3.4"

services:
  9kmmrbot:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    restart: unless-stopped
    command: ["node", "-r", "source-map-support/register",  "dist/index.js"]
  mongodb:
    image: "docker.io/bitnami/mongodb:4.4-debian-10"
    restart: unless-stopped
    volumes:
      - "mongodb_data:/bitnami/mongodb"
      - ./init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js

volumes:
  mongodb_data: